# Generated by Django 2.2 on 2020-09-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dogs', '0002_auto_20200912_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='birthday',
            field=models.DateField(verbose_name='дата рождения'),
        ),
    ]
