# Generated by Django 2.2 on 2020-09-16 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_dogs', '0003_auto_20200912_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogs',
            name='shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='название приюта'),
        ),
    ]
