# Generated by Django 2.2 on 2020-10-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dogs', '0004_dogs_shelter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='height',
            field=models.FloatField(verbose_name='рост'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='weight',
            field=models.FloatField(verbose_name='вес'),
        ),
    ]
