# Generated by Django 2.2 on 2020-10-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dogs', '0005_auto_20201015_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogs',
            options={'permissions': (('can_undelete', 'Can undelete this object'),)},
        ),
        migrations.AddField(
            model_name='dogs',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
    ]
